### ISSUE TITLE
Set the platform and the version.

### ISSUE THREAD

**Issue by ilvalerione** [inspector-apm/inspector-codeigniter#2]
You can inform the platform about the version of the library. This allow Inspector users to be notified when a new verision is released.

https://github.com/inspector-apm/inspector-codeigniter/blob/474e01441d568c7e28139e41fddfac5caf95ad4c/src/Inspector.php#L22

```php
class InspectorServiceProvider extends ServiceProvider
{
    /**
     * The latest version of the client library.
     *
     * @var string
     */
    const VERSION = '0.1.0';

    ...

    // Add this setting against the configuration instance.
    $configuration->setVersion(self::VERSION);
}
```

**Comment by benedict-tshaba** [comment]
This is a cool enhancement, and I think a nice value add. From which version of the inspector library is it available?

**Comment by ilvalerione** [comment]
It is available since the beginning.

To support more settings to the library's users via environment variables or CodeIgniter configuration system you can take inspiration from the initialization process in the Laravel package:

https://github.com/inspector-apm/inspector-laravel/blob/master/src/InspectorServiceProvider.php#L76
