### ISSUE TITLE
Unhandled Exceptions are no longer sent to the inspector dashboard

### ISSUE THREAD

**Issue by benedict-tshaba** [inspector-apm/inspector-codeigniter#6]
New in version 4.4.0. of CodeIgniter.

There has been a change in the way the framework handles exceptions, see https://codeigniter.com/user_guide/general/errors.html#using-exceptions

The issue now is that the default error/exception handler will be called instead of the libraries' recordUnhandledException method. This means that unhandled exceptions will not be recorded/reported to the inspector dashboard like they used to even if the config parameter LogUnhandledExceptions is set to true.

There is a quick work around for now, edit the handler method of app/Config/Exceptions.php to look like this:
```PHP
public function handler(int $statusCode, Throwable $exception): ExceptionHandlerInterface
{
    \Config\Services::inspector()->reportException($exception);
    return new ExceptionHandler($this);
}
```

Not really sure how to handle the issue in a 'nice' way currently. But will make a pull request once we have something solid.

**Comment by ilvalerione** [comment]
This incopatibility should be reflected in the composer.json file.

Maybe "codeigniter4/codeigniter4": ">=4.4.0" can make the job.

**Comment by benedict-tshaba** [comment]
> This incopatibility should be reflected in the composer.json file.
> 
> Maybe "codeigniter4/codeigniter4": ">=4.4.0" can make the job.

I don't think that is necessary, we have an Application that is running on CodeIgniter 4.3.2, and it is still working correctly with these changes. So this isn't really a breaking change.

i.e. The changes will still work for users who are on a previous version of the CodeIgniter framework.
